<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="LagoVista.Core.Authentication" />
    <PackageReference Include="LagoVista.MediaServices.Models" />
    <PackageReference Include="LagoVista.IoT.DeviceAdmin.Models" />
    <PackageReference Include="LagoVista.IoT.Deployment.Admin" />
    <PackageReference Include="LagoVista.IoT.DeviceAdmin" />
    <PackageReference Include="LagoVista.IoT.DeviceManagement.Core" />
    <PackageReference Include="LagoVista.PDFServices" />
    <PackageReference Include="LagoVista.UserAdmin" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\LagoVista.FSLite.Models\LagoVista.FSLite.Models.csproj" />
  </ItemGroup>
</Project>
