<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="LagoVista.CloudStorage" Version="7.0.5" />
    <PackageVersion Include="LagoVista.Core" Version="7.0.4" />
    <PackageVersion Include="LagoVista.Core.Authentication" Version="7.0.4" />
    <PackageVersion Include="LagoVista.Core.Configuration" Version="7.0.4" />
    <PackageVersion Include="LagoVista.Core.TestBase" Version="7.0.4" />
    <PackageVersion Include="LagoVista.IoT.Deployment.Admin" Version="7.0.3" />
    <PackageVersion Include="LagoVista.IoT.Deployment.Models" Version="7.0.3" />
    <PackageVersion Include="LagoVista.IoT.DeviceAdmin" Version="7.0.3" />
    <PackageVersion Include="LagoVista.IoT.DeviceAdmin.Models" Version="7.0.3" />
    <PackageVersion Include="LagoVista.IoT.DeviceManagement.Core" Version="7.0.3" />
    <PackageVersion Include="LagoVista.IoT.DeviceManagement.Models" Version="7.0.3" />
    <PackageVersion Include="LagoVista.IoT.Logging" Version="7.0.4" />
    <PackageVersion Include="LagoVista.IoT.Web.Common" Version="7.0.3" />
    <PackageVersion Include="LagoVista.MediaServices.Models" Version="7.0.4" />
    <PackageVersion Include="LagoVista.PDFServices" Version="7.0.4" />
    <PackageVersion Include="LagoVista.UserAdmin" Version="7.0.4" />
  </ItemGroup>
</Project>
