<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\LagoVista.FSLite.Admin\LagoVista.FSLite.Admin.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="LagoVista.Core.Configuration" />
    <PackageReference Include="LagoVista.CloudStorage" />
  </ItemGroup>
</Project>
